version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Shokku_Takku
      - public-data:/Shokku_Takku/public
      - tmp-data:/Shokku_Takku/tmp
      - log-data:/Shokku_Takku/log
    depends_on:
      - db
  # db:
  #   image: mysql:5.7
  #   env_file:
  #     - ./environments/db.env
  #   volumes:
  #     - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Shokku_Takku/public
      - tmp-data:/Shokku_Takku/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
